version: '3'
services:
  create:
    image: node:lts-stretch
    working_dir: "/app"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/
  app:
    image: node:lts-stretch
    working_dir: "/app"
    ports:
      - "3000:3000"
    command: sh -c "cd ${PROJ} && yarn start"
    volumes:
      - ./app:/app/
    tty: true
